version: 2

multi-ecosystem-groups:
  maintenance:
    schedule:
      interval: "monthly"
      time: "05:15"
      timezone: "America/Bogota"
    milestone: 3

updates:
  # ========================
  # Maintenance - ReactJS
  # ========================
  - package-ecosystem: "npm"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "maintenance"
    labels:
      - "javascript"
      - "dependencies"
    reviewers:
      - "Sleon4"

  # ========================
  # Security - ReactJS
  # ========================
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 3
    rebase-strategy: "auto"
    labels:
      - "javascript"
      - "security"
    reviewers:
      - "Sleon4"
    milestone: 3
